# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dashboard::Application.load_tasks

namespace :dashboard do
  puts "oooooooooooooooooooooooooooooooooooooo"
  task setup_db: ['db:setup_or_migrate', 'seed:default'] do
  puts "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  end
end
