---

dependencies:
  - role: apt_repo
    add_apt_key: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    third_party_repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
